### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by suminqi** [hikvision-research/SparseShiftLayer#2]
版本:
python 3.7.12
pytorch 1.12.1
cuda 11.3
ninja 1.10.2

Using C:\Users\XXXX\AppData\Local\torch_extensions\torch_extensions\Cache\py37_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\XXXX\AppData\Local\torch_extensions\torch_extensions\Cache\py37_cu113\ssl_cuda\build.ninja...
Building extension module ssl_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
Loading extension module ssl_cuda...
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    from models.SSL import SSL2d
  File "D:\XXXX\tool\git repository\SparseShiftLayer-main\models\SSL.py", line 23, in <module>
    verbose=True)XXXX
  File "D:\XXXX\anaconda\envs\yolov6_ssl_env\lib\site-packages\torch\utils\cpp_extension.py", line 1214, in load
    keep_intermediates=keep_intermediates)
  File "D:\XXXX\anaconda\envs\yolov6_ssl_env\lib\XXXXsite-packages\torch\utils\cpp_extension.py", line 1450, in _jit_compile
    return _import_moduleXXXX_from_library(name, build_directory, is_python_module)
  File "D:\XXXX\anaconda\envs\yolov6_ssl_env\lib\site-packages\torch\utils\cpp_extension.py", line 1844, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed: 找不到指定的模块

请问这个怎么解决/(ㄒoㄒ)/~~

**Comment by lockonlee** [comment]
Something wrong with relative file path. Please refer to the latest commit to fix this bug.
