### ISSUE TITLE
ImportError: No module named 'ssl_cuda'

### ISSUE THREAD

**Issue by zgebg** [hikvision-research/SparseShiftLayer#3]
python 3.6
pytorch 1.4.0
torchvison 0.2.1
ninja 1.10.2.3

项目运行报错：
Using /tmp/torch_extensions as PyTorch extensions root...
Creating extension directory /tmp/torch_extensions/ssl_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/ssl_cuda/build.ninja...
Building extension module ssl_cuda...
1.10.2
Loading extension module ssl_cuda...
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from models.SSL import SSL2d
  File "/root/SparseShiftLayer-main/models/SSL.py", line 23, in <module>
    verbose=True)
  File "/root/.local/conda/envs/fcos_3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 680, in load
    is_python_module)
  File "/root/.local/conda/envs/fcos_3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 877, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/root/.local/conda/envs/fcos_3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1084, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/root/.local/conda/envs/fcos_3.6/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'ssl_cuda'

**Comment by lockonlee** [comment]
Something wrong with relative file path. Please refer to the latest commit to fix this bug.
